---
version: "2"

services:
  api:
    image: ghcr.io/sylent-x/sylent-x-api
    container_name: sylent-x-api
    ports:
      - "3000:3000/tcp"
    environment:
        TZ: "Europe/Berlin"
        PORT: 3000
        ADDRESS: 10.0.0.2
    restart: always
    networks:
      sylent-x_net:
        ipv4_address: 10.0.0.2

networks:
  sylent-x_net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.0.0/29